#!/usr/bin/env node
/* ============================================================================
   Inline everything into one HTML file.

   Three targets, one composer:

       node build.js              → dist/index.html      the deliverable
       node build.js --3d         → + dist/index-3d.html  with the 3D presenter
       node build.js --artifact   → + dist/artifact.html  for a hosted Artifact
       node build.js --no-config  → omit config.js (composes with all of them)
       node build.js --no-voice   → omit the pre-rendered speech
       node build.js --require-voice
                                  → refuse to build unless the speech is
                                    complete and all-scope (the container)

   Every run rebuilds dist/index.html; the flags ADD targets rather than
   replacing it. So dist/index.html is never accidentally a 3D build.

   ── WHY THE SPEECH IS IN THE CANVAS TARGETS AND NOT THE 3D ONE ────────────
   assets/voice-clips.js is generated by tools/prerender-voice.mjs: every line
   the deck speaks, rendered ONCE through ElevenLabs and baked in as base64. It
   is what makes the shipped file sound like a person with no key, no network
   and no account — and it is several megabytes, so where it goes is a size
   decision made per target, exactly as TalkingHead and the GLB are.

   The canvas targets carry it because they are the ones that go out: the booth
   pod, the emailed file, the container, and dist/artifact.html, the hosted
   preview that a published Artifact's CSP has always denied a live voice. The
   3D target already spends ~10.4 MB on the vendor bundle and the avatar, so the
   speech would put it past its own ceiling on its own — it does not get it, and
   there is no flag to give it one. An unvoiced 3D build is not a broken one:
   src/voice.js falls through to the live API or to Web Speech, precisely as it
   did before any of this.

   A consequence worth stating, because it is the whole reason the container
   needs no API key: at --scope all the payload covers EVERY string the deck can
   speak — the twelve scenes' narration, all 39 knowledge-base answers, and
   DONT_KNOW, which src/ask.js returns for anything it cannot answer. With that
   file present there is no runtime text left to synthesise, so the image ships
   with no ElevenLabs credential at all and cannot leak one. --require-voice is
   what turns that from an intention into something the build enforces; without
   it, a missing or narration-scope payload produces a green build that answers
   questions in the robotic browser voice and says nothing about it.

   ── WHY THE 3D PRESENTER IS A SEPARATE FILE ───────────────────────────────
   dist/index.html has one promise and it is narrow and absolute: copy it to a
   booth machine, unplug the network, double-click it, press F11. That promise
   is why the fonts are data URIs and why there is no bundler here. It is also
   why this target carries NO TalkingHead bytes and NO avatar GLB: the vendor
   bundle is 0.8 MB and the base64 of the GLB is several times that, and a deck
   that takes ten seconds to paint has already lost the room.

   Nothing is lost by leaving them out. src/avatar3d.js is built so that
   Avatar3D.create() ANSWERS NULL rather than throwing when window.TalkingHead
   is missing, and the Presenter then uses the canvas bust — the same path a
   blocklisted GPU or prefers-reduced-motion takes. "No 3D in this file" is a
   size decision, never a broken page.

   The module inliner is deliberately small: it understands the handful of
   import/export forms this repo actually uses, in dependency order. It is not a
   bundler and does not pretend to be — if the import style changes, change this
   or reach for esbuild.
   ========================================================================== */

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const read = p => fs.readFileSync(path.join(ROOT, p), 'utf8');
const bytes = p => fs.readFileSync(path.join(ROOT, p));
const exists = p => fs.existsSync(path.join(ROOT, p));

/* Dependency order, leaves first. avatar3d.js imports avatar.js, presenter.js
   imports both it and voice.js, app.js imports presenter.js — so the two 3D
   files sit between voice.js and ask.js. Get this wrong and the built file
   still parses; it just dies at `Presenter is not defined` on first paint.

   src/icons.js is the deepest leaf — it imports nothing and both scenes.js and
   app.js import it — so it goes FIRST. Its exports are all prefixed (DXC_ICONS,
   DXC_MARK, dxcIcon, dxcMark, dxcHydrate) because two of the 48 icon names it
   carries, `pause` and `search`, are already top-level functions in this scope;
   assertNoCollisions() below is what keeps that honest. */
const MODULES = [
  'src/icons.js',
  'src/knowledge.js',
  'src/scenes.js',
  'src/avatar.js',
  'src/voice.js',
  'src/avatar3d.js',
  'src/presenter.js',
  'src/ask.js',
  'src/app.js',
];

/* ── the size ceilings, PER TARGET ────────────────────────────────────────
   One number covered all three targets while they were within a megabyte of
   each other. They are not any more, and they no longer grow for the same
   reason: the canvas targets carry the pre-rendered speech and the 3D target
   carries the avatar INSTEAD, so they move independently and are ~5 MB apart.
   A single cap set high enough for the larger stops constraining the smaller —
   it silently becomes a cap on nothing, which is the failure mode every shared
   threshold has.

   Each number below is the point past which that target stops doing its job,
   and each is derived from a constraint OUTSIDE this repo. A ceiling set just
   above what the build measures today catches the thing it was written for
   exactly never; it only ratchets upward each time someone hits it. */
const SIZE_LIMITS_MB = {
  /* The canvas targets are the ones that GO OUT — emailed, carried on a stick,
     opened from a booth desktop. Email is the binding constraint and it is not
     ours to negotiate: the common attachment ceiling is 25 MB, and MIME base64
     inflates an attachment by a third in transit, so anything above ~18.7 MB
     cannot be sent at all. 18 is that, rounded down.

     What it protects against: the speech is the one input here that scales with
     CONTENT rather than with a single asset. Every knowledge-base entry added is
     another clip, and re-rendering the corpus at a higher bitrate multiplies all
     of it at once — mp3_44100_128 is four times the size of the mp3_22050_32
     these are rendered at, and would carry a perfectly compliant build straight
     past this line without one source file changing. Before this existed the
     canvas targets had NO ceiling at all; the 12 MB one only ever tested the 3D
     file, so the target that actually ships was the unguarded one. */
  canvas: 18,

  /* Unchanged, and so is the reason for it: the GLB is the one input whose size
     can change by an order of magnitude without anyone touching this file, and
     base64 adds a third on top. Past 12 MB a single HTML file stops being a
     thing you can hand somebody.

     It keeps the tighter number because it does NOT carry the speech and does
     not grow when the voice scope does — `--scope all` costs this target
     nothing. It is also the cap with the least headroom of the two (measured
     11.20 MB against 12), which is the guard biting rather than slack. */
  three: 12,
};

/** Strip ES module syntax so the files can share one classic script scope. */
function flatten(src) {
  return src
    // import ... from '...';  /  import '...';
    .replace(/^\s*import\s+[^;]*?from\s*['"][^'"]+['"]\s*;?\s*$/gm, '')
    .replace(/^\s*import\s*['"][^'"]+['"]\s*;?\s*$/gm, '')
    // export const/let/function/class → plain declaration
    .replace(/^\s*export\s+(?=(const|let|var|function|class|async))/gm, '')
    // export { ... };
    .replace(/^\s*export\s*\{[^}]*\}\s*;?\s*$/gm, '')
    .replace(/^\s*export\s+default\s+/gm, 'const __default = ');
}

/* Flattening puts every module in one scope, so two modules that each declare a
   private `sleep` become a SyntaxError that only shows up in the built file.
   Catch it here rather than in a browser on a stand. */
function assertNoCollisions(flattened) {
  const owners = new Map();
  const problems = [];
  for (const [file, src] of flattened) {
    const names = new Set();
    // column 0 only — anything indented is inside a function and cannot collide
    for (const m of src.matchAll(/^(?:const|let|var|function|class|async function)\s+([A-Za-z_$][\w$]*)/gm)) {
      names.add(m[1]);
    }
    for (const n of names) {
      if (owners.has(n)) problems.push(`${n} — declared in both ${owners.get(n)} and ${file}`);
      else owners.set(n, file);
    }
  }
  if (problems.length) {
    console.error('top-level name collisions — the built file would not parse:');
    problems.forEach(p => console.error('  ✗ ' + p));
    process.exit(1);
  }
}

/* ── the one function every splice goes through ───────────────────────────
   Replace once, LITERALLY, and fail loudly if the seam has moved. Two separate
   traps, both of which produce a build that "succeeds":

   1. $-EXPANSION. String.replace(re, string) is not a literal splice — it
      expands $&, $1, $` and $' IN THE REPLACEMENT. vendor/talkinghead.bundle.js
      contains exactly one `$&`, in minified three.js:

          turn{setMask:function($){re!==$&&!P&&(o.colorMask($,$,$,$),re=

      `$&` means "the text that was matched", so splicing the bundle in as a
      string re-inserts the <script src="vendor/talkinghead.bundle.js"></script>
      tag it was replacing into the middle of the bundle. The symptoms are
      `Unexpected token '<'`, the entire payload failing to parse, and ~8800px
      of horizontal overflow — from a character nobody typed, in a file nobody
      reads. Passing a FUNCTION opts out of $-expansion completely: its return
      value is used verbatim. So every splice goes through here, including the
      CSS/JS/config ones that are only safe today because no source in this repo
      happens to contain a `$&` yet. That is not a property worth depending on.

   2. A SILENT MISS. index.html belongs to another task. Reformat one of these
      tags and the regex stops matching, .replace() returns the string
      unchanged, and the build ships a page that loads nothing at all. No match,
      no build. */
function splice(html, re, text, what) {
  if (!re.test(html)) {
    console.error(`build.js: the ${what} seam is not in index.html.`);
    console.error(`  looking for: ${re}`);
    console.error('  index.html says these tags are matched literally. If one was');
    console.error('  renamed or reformatted, update the pattern here to match it.');
    process.exit(1);
  }
  return html.replace(re, () => text);
}

/* ── the other kind of seam: a POSITION rather than a replacement ─────────
   The artifact target does not replace these tags, it CUTS AT them, so it
   needs offsets rather than splice(). That is the only reason they were raw
   indexOf() — and it made them the two seams in this file that fail SILENTLY,
   because indexOf answers -1 instead of throwing and -1 is a usable offset.

   Both traps produce a build that exits 0:

   1. `<body>` GAINS AN ATTRIBUTE (<body class="dxc-2026">). indexOf → -1,
      slice(-1 + 6) = slice(5), and the "body" now starts five characters into
      `<!doctype html>` — so the doctype, <html>, <head> and the whole ~762 KB
      inlined <style> are copied into the artifact a second time. The file goes
      945 KB → 1.71 MB. Loud, but only by luck: what catches it today is the
      1.4 MB cap in tests/build.test.mjs, which reports it as a SIZE failure and
      sends you looking at the fonts.

   2. `<style>` GAINS AN ATTRIBUTE. indexOf → -1, slice(-1, N) is empty, and the
      artifact ships with NO CSS AT ALL. It gets SMALLER, so every size
      assertion passes; nothing else asserted the artifact contains any CSS.
      That one is silent end to end and it is exactly what a brand pass trips.

   So: no literal, no build. The message names the literal that moved, because
   the person reading it is holding a reformatted index.html and needs to know
   which tag this file was promised. */
function at(html, literal, what, { last = false } = {}) {
  const i = last ? html.lastIndexOf(literal) : html.indexOf(literal);
  if (i < 0) {
    console.error(`build.js: cannot find ${JSON.stringify(literal)} — the ${what} seam has moved.`);
    console.error('  dist/artifact.html is cut out of the canvas build by OFFSET, so this tag is');
    console.error('  matched literally. If it was renamed, reformatted, or given an attribute,');
    console.error('  update the literal here to match it.');
    // Where to look, because it is not the same file for both tags and the
    // <style> one sends people grepping index.html for a tag that was never in it.
    console.error(literal.includes('style')
      ? '  NOTE: <style> is not in index.html — THIS file emits it, at the styles.css seam above.'
      : '  It is in index.html.');
    process.exit(1);
  }
  return i;
}

/* Seam S5 — the two OPTIONAL classic scripts at the bottom of index.html.
   Matched literally, which is the promise index.html's comment makes on this
   file's behalf. */
const TAG_VENDOR = /<script src="vendor\/talkinghead\.bundle\.js"><\/script>\n?/;
const TAG_GLB = /<script src="assets\/avatar-glb\.js"><\/script>\n?/;

/**
 * The `window.AIB_AVATAR_GLB_B64 = '...'` shim, or null if there is no avatar.
 *
 * It has to be base64 in the page rather than a URL to fetch: Chrome CORS-blocks
 * fetch() of a file:// URL even for a sibling file, so a relative assets/avatar.glb
 * cannot load from a double-clicked page. src/avatar3d.js turns the base64 back
 * into a Blob object URL. docs/TALKINGHEAD.md trap 3.
 *
 * assets/avatar-glb.js is generated (and validated) elsewhere, so prefer it when
 * it is on disk. Falling back to encoding assets/avatar.glb here is what stops a
 * stale-or-missing generated file silently shipping a 3D build with no avatar in
 * it — the visible symptom of which is, unhelpfully, the canvas bust.
 */
function avatarGlbShim() {
  if (exists('assets/avatar-glb.js')) {
    return { js: read('assets/avatar-glb.js'), from: 'assets/avatar-glb.js', glbBytes: 0 };
  }
  if (exists('assets/avatar.glb')) {
    const raw = bytes('assets/avatar.glb');
    // base64's alphabet is [A-Za-z0-9+/=] — no quote, no backslash, no `</script`
    // and no `$`, so this is safe both to quote and to inline. The GLB is the
    // only input here for which that is worth stating rather than assuming.
    return {
      js: `window.AIB_AVATAR_GLB_B64 = "${raw.toString('base64')}";`,
      from: 'assets/avatar.glb',
      glbBytes: raw.length,
    };
  }
  return null;
}

/**
 * The `window.AIB_VOICE_CLIPS = {...}` payload, or null if nothing is rendered.
 *
 * Same shape of decision as avatarGlbShim() above, and the same reason for it:
 * assets/voice-clips.js is GENERATED (tools/prerender-voice.mjs) and gitignored,
 * because it is megabytes of base64 that a script plus a key reproduces exactly.
 * A clone with no key has no such file, and every target below must build
 * byte-for-byte as it did before this existed. That is the whole contract:
 *
 *     present → the deck speaks in the real voice, offline, forever
 *     absent  → src/voice.js reads a miss and falls through, as it always did
 *
 * Nothing here parses it. It is one assignment statement produced by a tool that
 * already validated it, and re-parsing ten megabytes of base64 on every build to
 * re-learn what the tool printed would cost a second and prove nothing.
 */
function voiceClipsPayload() {
  if (!exists('assets/voice-clips.js')) return null;
  const js = read('assets/voice-clips.js');
  // The header comment the generator writes carries the counts; lift them for
  // the build log so the operator sees what is in the file without opening a
  // ten-megabyte line.
  const note = (js.match(/^\/\* voice-clips: ([^*]*)\*\//) || [])[1];
  /* `scope` and `corpus`/`n` are read off the ASSIGNMENT, not the header
     comment, because --require-voice below refuses a build on them and a
     decorative comment is not a thing to refuse a build on.

     Only the first 512 bytes are searched, which is what makes these three
     regexes safe on a ten-megabyte line. The generator emits its keys in a
     fixed order (v, format, model, voice, scope, n, corpus, ms, ... clips), so
     all three sit in the first couple of hundred characters, well ahead of the
     clip data — and base64's alphabet contains no double quote, so a match
     cannot come from inside an audio payload even in principle. This is still
     not parsing the file: ten megabytes of base64 is re-read to learn nothing
     the generator did not already print. */
  const head = js.slice(0, 512);
  const scope = (head.match(/"scope":"([a-z]+)"/) || [])[1] || null;
  const n = Number((head.match(/"n":(\d+)/) || [])[1]);
  const corpus = Number((head.match(/"corpus":(\d+)/) || [])[1]);
  return {
    js, bytes: Buffer.byteLength(js, 'utf8'), note: (note || '').trim(),
    scope, n, corpus,
  };
}

/* ── --require-voice ──────────────────────────────────────────────────────
   Refuse to produce a build that LOOKS voiced and is not.

   This exists because the failure it catches is completely silent. The image
   the operator ships is "host and run" — no ElevenLabs key inside it — and that
   promise holds for exactly one reason: every string the deck can speak was
   pre-rendered, so there is nothing left at runtime to synthesise. The moment
   the payload is missing, narration-scope, or short of the corpus, src/voice.js
   reads a miss and falls straight through to the browser's speechSynthesis. The
   build still exits 0. The page still loads. The deck still talks. It simply
   does it in the robotic voice this whole mechanism was built to get rid of,
   and nothing anywhere says so.

   The three cases it names, all of which have happened or nearly have:

     · NO FILE — assets/voice-clips.js is generated and gitignored, so a fresh
       clone has none. Whether the image speaks was therefore a property of
       whose machine packaged it, which is not a property a deliverable may have.
     · WRONG SCOPE — the default is `narration`, which renders the twelve scenes
       and no answers. That image narrates beautifully and answers every single
       question robotically, which is the worst of the three because it passes a
       casual check.
     · SHORT OF THE CORPUS — a clip is addressed by the text it speaks, so
       editing one narration line changes its key and drops it silently out of
       both the cache and the payload. Nothing else notices; that one line goes
       robotic mid-walkthrough.

   Deliberately NOT implied by anything. It is opt-in so that the tracked,
   unvoiced dist/ pair and a keyless clone both still build, and the Dockerfile
   passes it because the image is the artifact where the promise is made. */
function assertVoiceComplete(clips, { withVoice }) {
  const die = lines => {
    console.error('');
    console.error('REFUSING TO BUILD: --require-voice was asked for and this build is not voiced.');
    console.error('');
    lines.forEach(l => console.error(l));
    console.error('');
    process.exit(1);
  };

  /* Both flags at once is incoherent, and it is worth stopping ON rather than
     resolving by whichever is tested first. --no-voice says omit the speech;
     --require-voice says refuse to build without it. Picking a winner quietly
     would make the next person's "add --no-voice to get the build green" into a
     working way to paper over exactly the fault this flag exists to surface. */
  if (!withVoice) {
    die([
      '--no-voice and --require-voice contradict each other: one omits the speech,',
      'the other refuses to build without it. Nothing can satisfy both.',
      '',
      'Fix: drop whichever one you did not mean. --no-voice builds the unvoiced',
      'pair that is committed to dist/; --require-voice is for the container.',
    ]);
  }

  if (!clips) {
    die([
      'There is no assets/voice-clips.js. It is GENERATED and gitignored, so a',
      'clone does not have one and the deck would fall back to the browser\'s',
      'speechSynthesis — the robotic voice — for every line it speaks.',
      '',
      'Fix, once, on a machine with a key:',
      '  node tools/prerender-voice.mjs --scope all',
    ]);
  }

  if (clips.scope !== 'all') {
    die([
      `assets/voice-clips.js was rendered at scope ${JSON.stringify(clips.scope)}, not "all".`,
      '',
      'Only "all" covers the knowledge-base answers. A narration-scope payload',
      'narrates the twelve scenes in the real voice and answers every question a',
      'viewer asks in the robotic one — which looks correct right up until',
      'somebody asks something.',
      '',
      'Fix:',
      '  node tools/prerender-voice.mjs --scope all',
    ]);
  }

  if (!Number.isFinite(clips.corpus) || !Number.isFinite(clips.n)) {
    die([
      'assets/voice-clips.js does not record "n"/"corpus", so its completeness',
      'cannot be checked. It predates that field.',
      '',
      'Fix — this needs no API calls, it repacks the cache you already have:',
      '  node tools/prerender-voice.mjs --pack-only --scope all',
    ]);
  }

  if (clips.n < clips.corpus) {
    die([
      `assets/voice-clips.js carries ${clips.n} of ${clips.corpus} clips — ${clips.corpus - clips.n} are missing.`,
      '',
      'A clip is addressed by the exact text it speaks, so an edit to a narration',
      'line or a knowledge-base answer changes its key and drops it out of the',
      'payload. Those lines, and only those, would speak in the robotic voice.',
      '',
      'Fix — renders only what actually changed; everything else is cached:',
      '  node tools/prerender-voice.mjs --scope all',
    ]);
  }
}

const mb = n => (n / 1024 / 1024).toFixed(2) + ' MB';

function write(name, html) {
  const out = path.join(ROOT, 'dist', name);
  fs.writeFileSync(out, html);
  // Byte length, not html.length: the sources are full of em dashes and arrows,
  // and a UTF-16 code-unit count under-reports the file you actually ship.
  return Buffer.byteLength(html, 'utf8');
}

function build({ withConfig = true, want3d = false, wantArtifact = false,
  withVoice = true, requireVoice = false } = {}) {
  const shell = read('index.html');
  const css = read('assets/fonts.css') + '\n' + read('src/styles.css');
  const flattened = MODULES.map(m => [m, flatten(read(m))]);
  assertNoCollisions(flattened);
  const js = flattened.map(([m, src]) => `/* ─── ${m} ${'─'.repeat(Math.max(0, 58 - m.length))} */\n` + src)
    .join('\n\n');

  const configJs = withConfig && exists('config.js') ? read('config.js') : '';

  /* Everything common to all three targets. The S5 tags are deliberately left
     in place here — each target below decides what becomes of them. */
  let base = shell;
  base = splice(base, /<link rel="stylesheet" href="assets\/fonts\.css">\s*\n?/, '', 'fonts.css');
  base = splice(base, /<link rel="stylesheet" href="src\/styles\.css">/, `<style>\n${css}\n</style>`, 'styles.css');
  base = splice(base, /<script src="config\.js"[^>]*><\/script>/,
    configJs ? `<script>\n${configJs}\n</script>` : '<script>window.AIB_CONFIG = window.AIB_CONFIG || {};</script>',
    'config.js');

  /* The app seam is spliced PER TARGET rather than here, because it is the one
     thing the three targets disagree about now: the speech payload rides in
     front of the app, and the 3D target does not carry it. */
  const APP_SEAM = /<script type="module" src="src\/app\.js"><\/script>/;
  const clips = withVoice ? voiceClipsPayload() : null;
  /* Before a single byte is written. A build that is going to be refused should
     not leave a half-correct dist/ behind for someone to pick up by mistake. */
  if (requireVoice) assertVoiceComplete(clips, { withVoice });
  /* Its own script element, ahead of the app's. Ahead because src/voice.js
     reads window.AIB_VOICE_CLIPS at call time and app.js constructs Voice on
     load; separate because a multi-megabyte string literal has no business
     sharing a parse unit with the code, and because that is how the GLB and the
     vendor bundle already ride. */
  const appScript = voiced => (voiced && clips ? `<script>\n${clips.js}\n</script>\n` : '')
    + `<script>\n${js}\n</script>`;

  fs.mkdirSync(path.join(ROOT, 'dist'), { recursive: true });

  /* ── target 1: dist/index.html — the deliverable ─────────────────────────
     Both S5 tags come OUT rather than being left to 404. A missing relative
     script under file:// is ERR_FILE_NOT_FOUND: four red lines in the console
     of a machine on a stand, and shoot.js counts console errors as failures. */
  let canvas = splice(base, TAG_VENDOR, '', 'TalkingHead bundle');
  canvas = splice(canvas, TAG_GLB, '', 'avatar GLB');
  canvas = splice(canvas, APP_SEAM, appScript(true), 'app.js');
  const indexBytes = write('index.html', canvas);

  const kb = (read('src/knowledge.js').match(/^\s*id:\s*'/gm) || []).length;
  const scenes = (read('src/scenes.js').match(/^\s*id:\s*'/gm) || []).length;
  console.log(`dist/index.html     ${mb(indexBytes)}  canvas presenter, no network`);
  console.log(`  ${scenes} scenes · ${kb} knowledge entries · config ${configJs ? 'INLINED' : 'omitted'}`);
  console.log(`  speech ${clips ? `INLINED ${mb(clips.bytes)}${clips.note ? ` · ${clips.note}` : ''}` : 'omitted — Web Speech will narrate'}`);
  if (!clips && withVoice) {
    console.log('     no assets/voice-clips.js. Render it once with a key on the machine:');
    console.log('     node tools/prerender-voice.mjs');
  }
  if (configJs) console.log('  ⚠  a key is baked into this file — do not hand it out');

  /* The canvas ceiling. Checked here rather than once at the end because this
     is the file the promise is about, and because artifact.html is cut out of
     this exact string below — if this one is too big to send, so is that one. */
  if (indexBytes > SIZE_LIMITS_MB.canvas * 1024 * 1024) {
    console.log('');
    console.log(`  ⚠⚠  ${mb(indexBytes)} — this is NOT a deliverable (the ceiling is ~${SIZE_LIMITS_MB.canvas} MB).`);
    console.log('      Past this it cannot be emailed: a 25 MB attachment limit is ~18.7 MB of');
    console.log('      file once MIME base64 has taken its third.');
    if (clips) {
      console.log(`      The speech is ${mb(clips.bytes)} of it${clips.note ? ` (${clips.note})` : ''}.`);
      console.log('      Check the render format first — mp3_22050_32 is the one this is sized for:');
      console.log('      node tools/prerender-voice.mjs --plan --scope all');
    }
    console.log('');
  }


  /* ── target 2: dist/index-3d.html — the same page, plus the presenter ──── */
  if (want3d) {
    const vendorJs = exists('vendor/talkinghead.bundle.js') ? read('vendor/talkinghead.bundle.js') : null;
    const shim = avatarGlbShim();

    let three = vendorJs
      ? splice(base, TAG_VENDOR, `<script>\n${vendorJs}\n</script>`, 'TalkingHead bundle')
      : splice(base, TAG_VENDOR, '', 'TalkingHead bundle');
    three = shim
      ? splice(three, TAG_GLB, `<script>\n${shim.js}\n</script>`, 'avatar GLB')
      : splice(three, TAG_GLB, '', 'avatar GLB');
    three = splice(three, APP_SEAM, appScript(false), 'app.js');

    const threeBytes = write('index-3d.html', three);
    const parts = [
      vendorJs ? `TalkingHead ${mb(Buffer.byteLength(vendorJs, 'utf8'))}` : null,
      shim ? `GLB from ${shim.from}` : null,
    ].filter(Boolean).join(' · ');
    console.log(`dist/index-3d.html  ${mb(threeBytes)}  ${parts || 'nothing to add — see below'}`);

    if (!vendorJs) {
      console.log('  ⚠  vendor/talkinghead.bundle.js is missing, so this file has no 3D in it.');
      console.log('     Regenerate it with: npm ci && node vendor/build-vendor.mjs');
    }
    if (!shim) {
      console.log('  ⚠  no assets/avatar-glb.js and no assets/avatar.glb — this file will');
      console.log('     fall back to the canvas bust. See docs/TALKINGHEAD.md.');
    }
    if (clips) {
      console.log(`  ·  the speech (${mb(clips.bytes)}) is deliberately NOT in this file — it would`);
      console.log(`     put it at ${mb(threeBytes + clips.bytes)}, past its ${SIZE_LIMITS_MB.three} MB ceiling. See the note at the top.`);
    }

    if (threeBytes > SIZE_LIMITS_MB.three * 1024 * 1024) {
      // Loud on purpose. An HTML file this big is not a thing you email, put on
      // a stick, or open on a booth laptop, and the cause is always the same.
      console.log('');
      console.log(`  ⚠⚠  ${mb(threeBytes)} — this is NOT a deliverable (the ceiling is ~${SIZE_LIMITS_MB.three} MB).`);
      if (shim && shim.glbBytes) {
        console.log(`      assets/avatar.glb is ${mb(shim.glbBytes)}; base64 makes that ~${mb(shim.glbBytes * 4 / 3)}.`);
      } else if (shim) {
        console.log(`      The payload is ${shim.from}; the GLB behind it needs compressing.`);
      }
      console.log('      Compress the avatar first:  node tools/convert-valid-avatar.mjs');
      console.log('      A rigged, viseme-complete avatar belongs in the 2-3 MB range.');
      console.log('');
    }
  }

  /* ── target 3: dist/artifact.html ────────────────────────────────────────
     A Claude Artifact supplies its own <!doctype>/<head>/<body> and wraps what
     it is given, so the hosted preview needs the same page with that
     scaffolding removed and the theme stamped by script instead of on <html>.

     Built from the CANVAS page, never the 3D one, and that is not a size
     decision: a published Artifact's CSP blocks external hosts, and an inline
     payload of tens of megabytes would not survive the round trip anyway. */
  if (wantArtifact) {
    /* Every offset below goes through at(), and the lengths come off the
       literals rather than being typed as 6 and 8 — the two magic numbers that
       silently become wrong the moment a tag gains an attribute. */
    const BODY = '<body>', BODY_END = '</body>', STYLE = '<style>', STYLE_END = '</style>';
    const body = canvas
      .slice(at(canvas, BODY, 'artifact <body>') + BODY.length,
        at(canvas, BODY_END, 'artifact </body>', { last: true }))
      .trim();
    const head = canvas.slice(at(canvas, STYLE, 'artifact <style>'),
      at(canvas, STYLE_END, 'artifact </style>') + STYLE_END.length);
    /* This <title> is typed here rather than sliced out of index.html, because
       the <head> cut below starts at <style> and leaves index.html's own title
       behind. So it is a SECOND copy of the product name: rename the product and
       both this line and index.html have to move, or the hosted artifact keeps
       the old name while the deliverable has the new one. */
    const artifactBytes = write('artifact.html',
      `<title>Intelligent Airport — walkthrough</title>\n${head}\n` +
      `<script>document.documentElement.dataset.theme = ` +
      `localStorage.getItem('aib-theme') || 'dark';</script>\n${body}\n`);
    console.log(`dist/artifact.html  ${mb(artifactBytes)}  head/body scaffolding stripped for hosting`);
  }
}

build({
  withConfig: !process.argv.includes('--no-config'),
  want3d: process.argv.includes('--3d'),
  wantArtifact: process.argv.includes('--artifact'),
  withVoice: !process.argv.includes('--no-voice'),
  requireVoice: process.argv.includes('--require-voice'),
});
